services:
  - type: web
    name: securecloud
    env: java
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/securecloudapp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
